# -------- Stage 1 : Maven Build --------
FROM maven:3.9.6-eclipse-temurin-17 AS builder

WORKDIR /app

COPY pom.xml .
COPY . .

RUN mvn clean package -DskipTests


# -------- Stage 2 : Serve React --------
FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*

# Copy React build (generated by Maven)
COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
